name       : shairplay
version    : 139  # git rev-list --count ce80e0059 (2016-01-01)
release    : 1
source     :
    - git|https://github.com/juhovh/shairplay.git : ce80e005908f41d0e6fde1c4a21e9cb8ee54007b
license    :
    - BSD-3-Clause
    - LGPL-2.1
    - MIT
component  : desktop.multimedia
summary    : Apple airplay and raop protocol server
description: |
    Free portable AirPlay server implementation similar to ShairPort.
    Currently only AirPort Express emulation is supported.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(avahi-compat-libdns_sd)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
