name       : shairplay
version    : 148  # git rev-list --count 1782c369f (2018-07-18)
release    : 2
source     :
    - git|https://github.com/juhovh/shairplay.git : 1782c369fc23d7910da8d0ea4fd0343c8684e8dd
license    :
    - BSD-3-Clause
    - LGPL-2.1
    - MIT
component  : desktop.multimedia
summary    : Apple airplay and raop protocol server
description: |
    Free portable AirPlay server implementation similar to ShairPort.
    Currently only AirPort Express emulation is supported.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(avahi-compat-libdns_sd)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
